# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish to NuGet

on:
  push:
    tags:
      [ "v[0-9]+.[0-9]+.[0-9]+", "v[0-9]+.[0-9]+.[0-9]+-[0-9a-z]+" ]

jobs:
  build:

    env:
      SOLUTION: 'src\Rhythm.Drop.sln'

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
  
    - name: Set Version
      run: |
        echo "version=${GITHUB_REF_NAME/v/}" >> "$GITHUB_ENV"
        
    - name: Display Version
      run: |
       echo "Version: $version"
